name: CI

on: [push, pull_request]

jobs:
  build_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Upload the mod to Steam Workshop (if this is a release commit)
        uses: IsaacScript/isaac-steam-workshop-upload@main
        if: "contains(github.event.head_commit.message, 'chore: release') && github.event_name != 'pull_request'"
        with:
          mod_path: .
          ignore_files: cspell.json,release.py,release.sh,steam
          change_note: "Version: {VERSION}\n\nChanges for this mod are [url=https://github.com/Zamiell/racing-plus]tracked on GitHub[/url]."
        env:
          CONFIG_VDF_CONTENTS: ${{ secrets.CONFIG_VDF_CONTENTS }}

  discord:
    name: Discord Failure Notification
    needs: [build_and_lint]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: failure
          title: ""
